# fly.toml app configuration file generated for blogtracker on 2024-02-18T20:49:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blogtracker'
primary_region = 'arn'

[build]

[env]
  PORT = "3003" # add this

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

