name: Simple CI with ESLint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Frontend ESLint check
    - name: Install frontend dependencies
      run: npm install
      working-directory: bloglist-frontend

    - name: Run ESLint for frontend
      run: npm run lint
      working-directory: bloglist-frontend

    # Backend ESLint check
    - name: Install backend dependencies
      run: npm install
      working-directory: bloglist-backend