name: Simple CI with ESLint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Frontend ESLint check
    - name: Install frontend dependencies
      run: npm install
      working-directory: bloglist-frontend

    - name: Run ESLint for frontend
      run: npm run lint
      working-directory: bloglist-frontend

    # Frontend tests
    - name: Run frontend tests
      run: npm run test
      working-directory: bloglist-frontend

    # Backend ESLint check
    - name: Install backend dependencies
      run: npm install
      working-directory: bloglist-backend

    # Set environment variables for backend
    - name: Set environment variables for backend
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> .env
    
    # Backend tests
    - name: Run backend tests with environment variables
      run: npm run test && echo "NODE_ENV=${NODE_ENV}"
      working-directory: bloglist-backend
