name: Simple CI with ESLint

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Frontend Installing Dependencies
    - name: Install frontend dependencies
      run: npm install
      working-directory: bloglist-frontend

    # Frotnend ESLint check
    - name: Run ESLint for frontend
      run: npm run lint
      working-directory: bloglist-frontend

    # Frontend tests
    - name: Run frontend tests
      run: npm run test
      working-directory: bloglist-frontend


  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Setting up MongoDB with docker-compose
      - name: Set up MongoDB
        run: docker-compose -f docker-compose.dev.yml up -d mongodb
        working-directory: bloglist-backend

      # Setting up backend
      - name: Install backend dependencies
        run: npm install
        working-directory: bloglist-backend

      # Backend tests
      - name: Run backend tests with environment variables
        env:
          PORT: ${{ secrets.PORT }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          MONGODB_URI: ${{ secrets.MONGO_URI }}
        working-directory: bloglist-backend
        run:
          npm run test -- tests/database_connection.test.js

  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: bloglist-frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: bloglist-backend

      - name: Set up MongoDB
        run: docker-compose -f bloglist-backend/docker-compose.dev.yml up -d mongodb

      - name: Run Cypress tests
        run: npm run cypress:run
        working-directory: bloglist-frontend